### ISSUE TITLE
[온보딩] 크롤러 실행 방법 익히기

### ISSUE THREAD

**Issue by GoGiants1** [wafflestudio/siksha-crawler#78]
1. poetry 개발 환경 세팅
1. 환경 변수 사용해서 (aws systems manager), dev 크롤러 빌드 (리드미 참조)
1. 로컬에서 디버깅해보기(리드미 참조)
1. 빌드된 도커 이미지 실행
1. 서버 관련 레포 watch 설정

시도해보시고, 코멘트 남겨주세요~

**Comment by tictactoeid** [comment]
모두 완료했습니다!

**Comment by isuh88** [comment]
완료했습니다!!

**Comment by soobin-jeon** [comment]
완료했습니다!

**Comment by yknxh** [comment]
완료했습니당~~
