### ISSUE TITLE
크롤러 버그 '08:20~준비수량소진시까지'

### ISSUE THREAD

**Issue by GanziDaeyong** [wafflestudio/siksha-crawler#88]
**어떤 버그였나요?**

'08:20~준비수량소진시까지'가 메뉴로 잡힘

**해결 방안**

어느 크롤러에서 잡히는지 확인 -> 예외처리 -> DB에서 일괄 삭제

**Comment by tictactoeid** [comment]
(1),(2)중 선택 1
\*학기 중 일 200식 한정\*

위 2가지도 예외처리 필요
